### =====================================
### AULA 5: ROTAS DE DIAGNÓSTICO
### =====================================

### Teste rota principal fallback
GET http://localhost:3000/

### Testa integridade do sistema (Health Check)
GET http://localhost:3000/api/health

### Testar versão do sistema (Version Check)
GET http://localhost:3000/api/version

### Listar todas as tarefas (GET)
GET http://localhost:3000/api/tasks

### Adicionar nova tarefa (POST)
POST http://localhost:3000/api/tasks
Content-Type: application/json

{
    "title": "Minha nova tarefa do dia 12/08/2026"
}

### Deletar tarefa por Id (DELETE), http://URL/endpoint/id
DELETE http://localhost:3000/api/tasks/1786580752739